principalset_terraform_plan_gha_pr             = "principalSet://iam.googleapis.com/projects/643615470006/locations/global/workloadIdentityPools/github-kaito-tokyo/attribute.repository/kaito-tokyo/discord-mxptc-bot"
project_id                                     = "discord-mxptc-bot-1-svc-my1a"
region                                         = "asia-east1"
terraform_apply_gha_main_service_account_email = "mpb-terraform-apply-gha-main@discord-mxptc-bot-1-svc-my1a.iam.gserviceaccount.com"
tfstate_bucket_name                            = "tfstate-discord-mxptc-bot-1-svc-my1a"
