---
name: "terraform-fmt"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: "bash"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  TerraformFmt:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 10

    steps:
      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Run terraform fmt"
        run: "terraform fmt -check -diff -recursive terraform"
