---
name: "terraform-apply-main"

"on":
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/terraform-apply-main.yaml"
      - "terraform/**"

defaults:
  run:
    shell: "bash"
    working-directory: "terraform/environments/prod"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  TerraformApply:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 10

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Install dependencies"
        run: "apt-get update && apt-get install -y pack"

      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/643615470006/locations/global/workloadIdentityPools/github-kaito-tokyo/providers/actions-githubusercontent-com"
          service_account: "mpb-terraform-apply-gha-main@discord-mxptc-bot-1-svc-my1a.iam.gserviceaccount.com"

      - name: "Terraform Init"
        run: "terraform init"

      - name: "Terraform Plan"
        run: "terraform plan -input=false -out=tfplan"

      - name: "Terraform Apply"
        run: "terraform apply -input=false -auto-approve tfplan"