---
name: "terraform-apply-main"

"on":
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/terraform-apply-main.yaml"
      - "terraform/**"

defaults:
  run:
    shell: "bash"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  TerraformApply:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 10

    permissions:
      contents: "read"
      id-token: "write"
    
    environment: "prod"

    steps:
      - name: "Install BuildKit"
        working-directory: "/usr/local"
        run: |
          curl -fsSL https://github.com/moby/buildkit/releases/download/v0.14.0/buildkit-v0.14.0.linux-amd64.tar.gz | sudo tar -xzf -

      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/643615470006/locations/global/workloadIdentityPools/github-kaito-tokyo/providers/actions-githubusercontent-com"
          service_account: "mpb-terraform-apply-gha-main@discord-mxptc-bot-1-svc-my1a.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Authenticate Docker"
        run: "gcloud auth configure-docker asia-east1-docker.pkg.dev"
 
      - name: "Build Docker image"
        run: |
          sudo buildkitd &
          sleep 5
          ls -l /run/buildkit/buildkitd.sock
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=asia-east1-docker.pkg.dev/discord-mxptc-bot-1-svc-my1a/mxptc-bot/mxptc-bot:latest,push=true \
            --export-cache type=registry,ref=asia-east1-docker.pkg.dev/discord-mxptc-bot-1-svc-my1a/mxptc-bot/mxptc-bot-cache:latest \
            --import-cache type=registry,ref=asia-east1-docker.pkg.dev/discord-mxptc-bot-1-svc-my1a/mxptc-bot/mxptc-bot-cache:latest

      - name: "Terraform Init"
        working-directory: "terraform/environments/prod"
        run: "terraform init"

      - name: "Terraform Plan"
        working-directory: "terraform/environments/prod"
        run: "terraform plan -input=false -out=tfplan"

      - name: "Terraform Apply"
        working-directory: "terraform/environments/prod"
        run: "terraform apply -input=false -auto-approve tfplan"